/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kenvin' at '4/16/17 9:24 AM' with Gradle 2.14.1
 *
 * @author kenvin, @date 4/16/17 9:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
